// Auto-generated. Do not edit!

// (in-package ghm_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let ghm_Addint_2ActionGoal = require('./ghm_Addint_2ActionGoal.js');
let ghm_Addint_2ActionResult = require('./ghm_Addint_2ActionResult.js');
let ghm_Addint_2ActionFeedback = require('./ghm_Addint_2ActionFeedback.js');

//-----------------------------------------------------------

class ghm_Addint_2Action {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new ghm_Addint_2ActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new ghm_Addint_2ActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new ghm_Addint_2ActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ghm_Addint_2Action
    // Serialize message field [action_goal]
    bufferOffset = ghm_Addint_2ActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = ghm_Addint_2ActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = ghm_Addint_2ActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ghm_Addint_2Action
    let len;
    let data = new ghm_Addint_2Action(null);
    // Deserialize message field [action_goal]
    data.action_goal = ghm_Addint_2ActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = ghm_Addint_2ActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = ghm_Addint_2ActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += ghm_Addint_2ActionGoal.getMessageSize(object.action_goal);
    length += ghm_Addint_2ActionResult.getMessageSize(object.action_result);
    length += ghm_Addint_2ActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ghm_action/ghm_Addint_2Action';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2974ffe7cbeb74f10f5a85741513d783';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    ghm_Addint_2ActionGoal action_goal
    ghm_Addint_2ActionResult action_result
    ghm_Addint_2ActionFeedback action_feedback
    
    ================================================================================
    MSG: ghm_action/ghm_Addint_2ActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    ghm_Addint_2Goal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: ghm_action/ghm_Addint_2Goal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #目标值
    int32 num
    
    ================================================================================
    MSG: ghm_action/ghm_Addint_2ActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    ghm_Addint_2Result result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: ghm_action/ghm_Addint_2Result
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #最终结果
    int32 result
    
    ================================================================================
    MSG: ghm_action/ghm_Addint_2ActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    ghm_Addint_2Feedback feedback
    
    ================================================================================
    MSG: ghm_action/ghm_Addint_2Feedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #连续反馈
    float64 progress_bar
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ghm_Addint_2Action(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = ghm_Addint_2ActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new ghm_Addint_2ActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = ghm_Addint_2ActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new ghm_Addint_2ActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = ghm_Addint_2ActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new ghm_Addint_2ActionFeedback()
    }

    return resolved;
    }
};

module.exports = ghm_Addint_2Action;
