; Auto-generated. Do not edit!


(cl:in-package ghm_action-msg)


;//! \htmlinclude dowishResult.msg.html

(cl:defclass <dowishResult> (roslisp-msg-protocol:ros-message)
  ((total_dishes_cleaned
    :reader total_dishes_cleaned
    :initarg :total_dishes_cleaned
    :type cl:integer
    :initform 0))
)

(cl:defclass dowishResult (<dowishResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <dowishResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'dowishResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ghm_action-msg:<dowishResult> is deprecated: use ghm_action-msg:dowishResult instead.")))

(cl:ensure-generic-function 'total_dishes_cleaned-val :lambda-list '(m))
(cl:defmethod total_dishes_cleaned-val ((m <dowishResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ghm_action-msg:total_dishes_cleaned-val is deprecated.  Use ghm_action-msg:total_dishes_cleaned instead.")
  (total_dishes_cleaned m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <dowishResult>) ostream)
  "Serializes a message object of type '<dowishResult>"
  (cl:let* ((signed (cl:slot-value msg 'total_dishes_cleaned)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <dowishResult>) istream)
  "Deserializes a message object of type '<dowishResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'total_dishes_cleaned) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<dowishResult>)))
  "Returns string type for a message object of type '<dowishResult>"
  "ghm_action/dowishResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'dowishResult)))
  "Returns string type for a message object of type 'dowishResult"
  "ghm_action/dowishResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<dowishResult>)))
  "Returns md5sum for a message object of type '<dowishResult>"
  "65b06906f7c5d0c26e4d79da0d1da640")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'dowishResult)))
  "Returns md5sum for a message object of type 'dowishResult"
  "65b06906f7c5d0c26e4d79da0d1da640")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<dowishResult>)))
  "Returns full string definition for message of type '<dowishResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 定义结果~%int32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'dowishResult)))
  "Returns full string definition for message of type 'dowishResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 定义结果~%int32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <dowishResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <dowishResult>))
  "Converts a ROS message object to a list"
  (cl:list 'dowishResult
    (cl:cons ':total_dishes_cleaned (total_dishes_cleaned msg))
))
