; Auto-generated. Do not edit!


(cl:in-package ghm_action-msg)


;//! \htmlinclude dowishFeedback.msg.html

(cl:defclass <dowishFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass dowishFeedback (<dowishFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <dowishFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'dowishFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ghm_action-msg:<dowishFeedback> is deprecated: use ghm_action-msg:dowishFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <dowishFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ghm_action-msg:percent_complete-val is deprecated.  Use ghm_action-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <dowishFeedback>) ostream)
  "Serializes a message object of type '<dowishFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <dowishFeedback>) istream)
  "Deserializes a message object of type '<dowishFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<dowishFeedback>)))
  "Returns string type for a message object of type '<dowishFeedback>"
  "ghm_action/dowishFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'dowishFeedback)))
  "Returns string type for a message object of type 'dowishFeedback"
  "ghm_action/dowishFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<dowishFeedback>)))
  "Returns md5sum for a message object of type '<dowishFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'dowishFeedback)))
  "Returns md5sum for a message object of type 'dowishFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<dowishFeedback>)))
  "Returns full string definition for message of type '<dowishFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 连续反馈的结果~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'dowishFeedback)))
  "Returns full string definition for message of type 'dowishFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 连续反馈的结果~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <dowishFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <dowishFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'dowishFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
