; Auto-generated. Do not edit!


(cl:in-package ghm_action-msg)


;//! \htmlinclude dowishGoal.msg.html

(cl:defclass <dowishGoal> (roslisp-msg-protocol:ros-message)
  ((dishwasher_id
    :reader dishwasher_id
    :initarg :dishwasher_id
    :type cl:integer
    :initform 0))
)

(cl:defclass dowishGoal (<dowishGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <dowishGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'dowishGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ghm_action-msg:<dowishGoal> is deprecated: use ghm_action-msg:dowishGoal instead.")))

(cl:ensure-generic-function 'dishwasher_id-val :lambda-list '(m))
(cl:defmethod dishwasher_id-val ((m <dowishGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ghm_action-msg:dishwasher_id-val is deprecated.  Use ghm_action-msg:dishwasher_id instead.")
  (dishwasher_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <dowishGoal>) ostream)
  "Serializes a message object of type '<dowishGoal>"
  (cl:let* ((signed (cl:slot-value msg 'dishwasher_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <dowishGoal>) istream)
  "Deserializes a message object of type '<dowishGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'dishwasher_id) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<dowishGoal>)))
  "Returns string type for a message object of type '<dowishGoal>"
  "ghm_action/dowishGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'dowishGoal)))
  "Returns string type for a message object of type 'dowishGoal"
  "ghm_action/dowishGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<dowishGoal>)))
  "Returns md5sum for a message object of type '<dowishGoal>"
  "d4757b44b198f8f290eb8a424780d97c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'dowishGoal)))
  "Returns md5sum for a message object of type 'dowishGoal"
  "d4757b44b198f8f290eb8a424780d97c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<dowishGoal>)))
  "Returns full string definition for message of type '<dowishGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 定义目标值~%int32 dishwasher_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'dowishGoal)))
  "Returns full string definition for message of type 'dowishGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 定义目标值~%int32 dishwasher_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <dowishGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <dowishGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'dowishGoal
    (cl:cons ':dishwasher_id (dishwasher_id msg))
))
