; Auto-generated. Do not edit!


(cl:in-package ghm_action-msg)


;//! \htmlinclude ghm_Addint_2Goal.msg.html

(cl:defclass <ghm_Addint_2Goal> (roslisp-msg-protocol:ros-message)
  ((num
    :reader num
    :initarg :num
    :type cl:integer
    :initform 0))
)

(cl:defclass ghm_Addint_2Goal (<ghm_Addint_2Goal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ghm_Addint_2Goal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ghm_Addint_2Goal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ghm_action-msg:<ghm_Addint_2Goal> is deprecated: use ghm_action-msg:ghm_Addint_2Goal instead.")))

(cl:ensure-generic-function 'num-val :lambda-list '(m))
(cl:defmethod num-val ((m <ghm_Addint_2Goal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ghm_action-msg:num-val is deprecated.  Use ghm_action-msg:num instead.")
  (num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ghm_Addint_2Goal>) ostream)
  "Serializes a message object of type '<ghm_Addint_2Goal>"
  (cl:let* ((signed (cl:slot-value msg 'num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ghm_Addint_2Goal>) istream)
  "Deserializes a message object of type '<ghm_Addint_2Goal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ghm_Addint_2Goal>)))
  "Returns string type for a message object of type '<ghm_Addint_2Goal>"
  "ghm_action/ghm_Addint_2Goal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ghm_Addint_2Goal)))
  "Returns string type for a message object of type 'ghm_Addint_2Goal"
  "ghm_action/ghm_Addint_2Goal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ghm_Addint_2Goal>)))
  "Returns md5sum for a message object of type '<ghm_Addint_2Goal>"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ghm_Addint_2Goal)))
  "Returns md5sum for a message object of type 'ghm_Addint_2Goal"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ghm_Addint_2Goal>)))
  "Returns full string definition for message of type '<ghm_Addint_2Goal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#目标值~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ghm_Addint_2Goal)))
  "Returns full string definition for message of type 'ghm_Addint_2Goal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#目标值~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ghm_Addint_2Goal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ghm_Addint_2Goal>))
  "Converts a ROS message object to a list"
  (cl:list 'ghm_Addint_2Goal
    (cl:cons ':num (num msg))
))
