; Auto-generated. Do not edit!


(cl:in-package ghm_action-msg)


;//! \htmlinclude ghm_AddintResult.msg.html

(cl:defclass <ghm_AddintResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass ghm_AddintResult (<ghm_AddintResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ghm_AddintResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ghm_AddintResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ghm_action-msg:<ghm_AddintResult> is deprecated: use ghm_action-msg:ghm_AddintResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <ghm_AddintResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ghm_action-msg:result-val is deprecated.  Use ghm_action-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ghm_AddintResult>) ostream)
  "Serializes a message object of type '<ghm_AddintResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ghm_AddintResult>) istream)
  "Deserializes a message object of type '<ghm_AddintResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ghm_AddintResult>)))
  "Returns string type for a message object of type '<ghm_AddintResult>"
  "ghm_action/ghm_AddintResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ghm_AddintResult)))
  "Returns string type for a message object of type 'ghm_AddintResult"
  "ghm_action/ghm_AddintResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ghm_AddintResult>)))
  "Returns md5sum for a message object of type '<ghm_AddintResult>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ghm_AddintResult)))
  "Returns md5sum for a message object of type 'ghm_AddintResult"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ghm_AddintResult>)))
  "Returns full string definition for message of type '<ghm_AddintResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ghm_AddintResult)))
  "Returns full string definition for message of type 'ghm_AddintResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ghm_AddintResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ghm_AddintResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ghm_AddintResult
    (cl:cons ':result (result msg))
))
