; Auto-generated. Do not edit!


(cl:in-package ghm_action-msg)


;//! \htmlinclude ghm_Addint_2Feedback.msg.html

(cl:defclass <ghm_Addint_2Feedback> (roslisp-msg-protocol:ros-message)
  ((progress_bar
    :reader progress_bar
    :initarg :progress_bar
    :type cl:float
    :initform 0.0))
)

(cl:defclass ghm_Addint_2Feedback (<ghm_Addint_2Feedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ghm_Addint_2Feedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ghm_Addint_2Feedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ghm_action-msg:<ghm_Addint_2Feedback> is deprecated: use ghm_action-msg:ghm_Addint_2Feedback instead.")))

(cl:ensure-generic-function 'progress_bar-val :lambda-list '(m))
(cl:defmethod progress_bar-val ((m <ghm_Addint_2Feedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ghm_action-msg:progress_bar-val is deprecated.  Use ghm_action-msg:progress_bar instead.")
  (progress_bar m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ghm_Addint_2Feedback>) ostream)
  "Serializes a message object of type '<ghm_Addint_2Feedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'progress_bar))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ghm_Addint_2Feedback>) istream)
  "Deserializes a message object of type '<ghm_Addint_2Feedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress_bar) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ghm_Addint_2Feedback>)))
  "Returns string type for a message object of type '<ghm_Addint_2Feedback>"
  "ghm_action/ghm_Addint_2Feedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ghm_Addint_2Feedback)))
  "Returns string type for a message object of type 'ghm_Addint_2Feedback"
  "ghm_action/ghm_Addint_2Feedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ghm_Addint_2Feedback>)))
  "Returns md5sum for a message object of type '<ghm_Addint_2Feedback>"
  "ac7532a8a8f0d2be4f5284d94fee2d59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ghm_Addint_2Feedback)))
  "Returns md5sum for a message object of type 'ghm_Addint_2Feedback"
  "ac7532a8a8f0d2be4f5284d94fee2d59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ghm_Addint_2Feedback>)))
  "Returns full string definition for message of type '<ghm_Addint_2Feedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#连续反馈~%float64 progress_bar~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ghm_Addint_2Feedback)))
  "Returns full string definition for message of type 'ghm_Addint_2Feedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#连续反馈~%float64 progress_bar~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ghm_Addint_2Feedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ghm_Addint_2Feedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ghm_Addint_2Feedback
    (cl:cons ':progress_bar (progress_bar msg))
))
