// Generated by gencpp from file ghm_action/dowishActionGoal.msg
// DO NOT EDIT!


#ifndef GHM_ACTION_MESSAGE_DOWISHACTIONGOAL_H
#define GHM_ACTION_MESSAGE_DOWISHACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <ghm_action/dowishGoal.h>

namespace ghm_action
{
template <class ContainerAllocator>
struct dowishActionGoal_
{
  typedef dowishActionGoal_<ContainerAllocator> Type;

  dowishActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  dowishActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::ghm_action::dowishGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::ghm_action::dowishActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ghm_action::dowishActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct dowishActionGoal_

typedef ::ghm_action::dowishActionGoal_<std::allocator<void> > dowishActionGoal;

typedef boost::shared_ptr< ::ghm_action::dowishActionGoal > dowishActionGoalPtr;
typedef boost::shared_ptr< ::ghm_action::dowishActionGoal const> dowishActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ghm_action::dowishActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ghm_action::dowishActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ghm_action::dowishActionGoal_<ContainerAllocator1> & lhs, const ::ghm_action::dowishActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ghm_action::dowishActionGoal_<ContainerAllocator1> & lhs, const ::ghm_action::dowishActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ghm_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ghm_action::dowishActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ghm_action::dowishActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::dowishActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::dowishActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::dowishActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::dowishActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ghm_action::dowishActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60f4a7e0ef04765a56cde80c15e00af2";
  }

  static const char* value(const ::ghm_action::dowishActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60f4a7e0ef04765aULL;
  static const uint64_t static_value2 = 0x56cde80c15e00af2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ghm_action::dowishActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ghm_action/dowishActionGoal";
  }

  static const char* value(const ::ghm_action::dowishActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ghm_action::dowishActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"dowishGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ghm_action/dowishGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 定义目标值\n"
"int32 dishwasher_id\n"
;
  }

  static const char* value(const ::ghm_action::dowishActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ghm_action::dowishActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dowishActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ghm_action::dowishActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ghm_action::dowishActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::ghm_action::dowishGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GHM_ACTION_MESSAGE_DOWISHACTIONGOAL_H
