// Generated by gencpp from file ghm_action/dowishResult.msg
// DO NOT EDIT!


#ifndef GHM_ACTION_MESSAGE_DOWISHRESULT_H
#define GHM_ACTION_MESSAGE_DOWISHRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ghm_action
{
template <class ContainerAllocator>
struct dowishResult_
{
  typedef dowishResult_<ContainerAllocator> Type;

  dowishResult_()
    : total_dishes_cleaned(0)  {
    }
  dowishResult_(const ContainerAllocator& _alloc)
    : total_dishes_cleaned(0)  {
  (void)_alloc;
    }



   typedef int32_t _total_dishes_cleaned_type;
  _total_dishes_cleaned_type total_dishes_cleaned;





  typedef boost::shared_ptr< ::ghm_action::dowishResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ghm_action::dowishResult_<ContainerAllocator> const> ConstPtr;

}; // struct dowishResult_

typedef ::ghm_action::dowishResult_<std::allocator<void> > dowishResult;

typedef boost::shared_ptr< ::ghm_action::dowishResult > dowishResultPtr;
typedef boost::shared_ptr< ::ghm_action::dowishResult const> dowishResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ghm_action::dowishResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ghm_action::dowishResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ghm_action::dowishResult_<ContainerAllocator1> & lhs, const ::ghm_action::dowishResult_<ContainerAllocator2> & rhs)
{
  return lhs.total_dishes_cleaned == rhs.total_dishes_cleaned;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ghm_action::dowishResult_<ContainerAllocator1> & lhs, const ::ghm_action::dowishResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ghm_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ghm_action::dowishResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ghm_action::dowishResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::dowishResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::dowishResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::dowishResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::dowishResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ghm_action::dowishResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65b06906f7c5d0c26e4d79da0d1da640";
  }

  static const char* value(const ::ghm_action::dowishResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65b06906f7c5d0c2ULL;
  static const uint64_t static_value2 = 0x6e4d79da0d1da640ULL;
};

template<class ContainerAllocator>
struct DataType< ::ghm_action::dowishResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ghm_action/dowishResult";
  }

  static const char* value(const ::ghm_action::dowishResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ghm_action::dowishResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 定义结果\n"
"int32 total_dishes_cleaned\n"
;
  }

  static const char* value(const ::ghm_action::dowishResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ghm_action::dowishResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_dishes_cleaned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dowishResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ghm_action::dowishResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ghm_action::dowishResult_<ContainerAllocator>& v)
  {
    s << indent << "total_dishes_cleaned: ";
    Printer<int32_t>::stream(s, indent + "  ", v.total_dishes_cleaned);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GHM_ACTION_MESSAGE_DOWISHRESULT_H
