// Generated by gencpp from file ghm_action/dowishFeedback.msg
// DO NOT EDIT!


#ifndef GHM_ACTION_MESSAGE_DOWISHFEEDBACK_H
#define GHM_ACTION_MESSAGE_DOWISHFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ghm_action
{
template <class ContainerAllocator>
struct dowishFeedback_
{
  typedef dowishFeedback_<ContainerAllocator> Type;

  dowishFeedback_()
    : percent_complete(0.0)  {
    }
  dowishFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::ghm_action::dowishFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ghm_action::dowishFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct dowishFeedback_

typedef ::ghm_action::dowishFeedback_<std::allocator<void> > dowishFeedback;

typedef boost::shared_ptr< ::ghm_action::dowishFeedback > dowishFeedbackPtr;
typedef boost::shared_ptr< ::ghm_action::dowishFeedback const> dowishFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ghm_action::dowishFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ghm_action::dowishFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ghm_action::dowishFeedback_<ContainerAllocator1> & lhs, const ::ghm_action::dowishFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ghm_action::dowishFeedback_<ContainerAllocator1> & lhs, const ::ghm_action::dowishFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ghm_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ghm_action::dowishFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ghm_action::dowishFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::dowishFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::dowishFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::dowishFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::dowishFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ghm_action::dowishFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::ghm_action::dowishFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::ghm_action::dowishFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ghm_action/dowishFeedback";
  }

  static const char* value(const ::ghm_action::dowishFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ghm_action::dowishFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 连续反馈的结果\n"
"float32 percent_complete\n"
;
  }

  static const char* value(const ::ghm_action::dowishFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ghm_action::dowishFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dowishFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ghm_action::dowishFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ghm_action::dowishFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GHM_ACTION_MESSAGE_DOWISHFEEDBACK_H
