// Generated by gencpp from file ghm_action/ghm_Addint_2Goal.msg
// DO NOT EDIT!


#ifndef GHM_ACTION_MESSAGE_GHM_ADDINT_2GOAL_H
#define GHM_ACTION_MESSAGE_GHM_ADDINT_2GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ghm_action
{
template <class ContainerAllocator>
struct ghm_Addint_2Goal_
{
  typedef ghm_Addint_2Goal_<ContainerAllocator> Type;

  ghm_Addint_2Goal_()
    : num(0)  {
    }
  ghm_Addint_2Goal_(const ContainerAllocator& _alloc)
    : num(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> const> ConstPtr;

}; // struct ghm_Addint_2Goal_

typedef ::ghm_action::ghm_Addint_2Goal_<std::allocator<void> > ghm_Addint_2Goal;

typedef boost::shared_ptr< ::ghm_action::ghm_Addint_2Goal > ghm_Addint_2GoalPtr;
typedef boost::shared_ptr< ::ghm_action::ghm_Addint_2Goal const> ghm_Addint_2GoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator1> & lhs, const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator1> & lhs, const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ghm_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54b3c80efd6fae6e6ffff8a4b9facd69";
  }

  static const char* value(const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54b3c80efd6fae6eULL;
  static const uint64_t static_value2 = 0x6ffff8a4b9facd69ULL;
};

template<class ContainerAllocator>
struct DataType< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ghm_action/ghm_Addint_2Goal";
  }

  static const char* value(const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#目标值\n"
"int32 num\n"
;
  }

  static const char* value(const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ghm_Addint_2Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ghm_action::ghm_Addint_2Goal_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GHM_ACTION_MESSAGE_GHM_ADDINT_2GOAL_H
