// Generated by gencpp from file ghm_action/ghm_Addint_2Result.msg
// DO NOT EDIT!


#ifndef GHM_ACTION_MESSAGE_GHM_ADDINT_2RESULT_H
#define GHM_ACTION_MESSAGE_GHM_ADDINT_2RESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ghm_action
{
template <class ContainerAllocator>
struct ghm_Addint_2Result_
{
  typedef ghm_Addint_2Result_<ContainerAllocator> Type;

  ghm_Addint_2Result_()
    : result(0)  {
    }
  ghm_Addint_2Result_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> const> ConstPtr;

}; // struct ghm_Addint_2Result_

typedef ::ghm_action::ghm_Addint_2Result_<std::allocator<void> > ghm_Addint_2Result;

typedef boost::shared_ptr< ::ghm_action::ghm_Addint_2Result > ghm_Addint_2ResultPtr;
typedef boost::shared_ptr< ::ghm_action::ghm_Addint_2Result const> ghm_Addint_2ResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator1> & lhs, const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator1> & lhs, const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ghm_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ghm_action/ghm_Addint_2Result";
  }

  static const char* value(const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#最终结果\n"
"int32 result\n"
;
  }

  static const char* value(const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ghm_Addint_2Result_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ghm_action::ghm_Addint_2Result_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ghm_action::ghm_Addint_2Result_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GHM_ACTION_MESSAGE_GHM_ADDINT_2RESULT_H
